FROM python:3.11-slim

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    libpq-dev \
    nano \
    tesseract-ocr \
    ffmpeg \
    flac \
    libavcodec-extra \
    libavformat-dev \
    libavutil-dev \
    libswscale-dev \
    && rm -rf /var/lib/apt/lists/*



COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY ./src /app
COPY .env /app/.env

RUN adduser --disabled-password --gecos '' appuser
USER appuser

ENV PORT=8000
ENV PATH="/usr/bin:${PATH}"

RUN chmod +x /usr/bin/ffmpeg /usr/bin/ffprobe

CMD uvicorn main:app --host 0.0.0.0 --port $PORT --reload